-- Pratice Problems

-- 1.

CREATE VIEW EMP_DEPT AS
SELECT EMP_ID, F_NAME, L_NAME, DEP_ID FROM Employees;

-- 2.

CREATE OR REPLACE VIEW EMPT_DEPT AS
SELECT EMP_ID, F_NAME, L_NAME, DEP_NAME
	FROM Employees, Departments
WHERE EMPLOYEES.DEP_ID = DEPARTMENTS.DEPT_ID_DEP;

--- 3
DROP VIEW EMPT_DEPT;