--  Practice problems

CREATE TABLE TOYS(
	ID INTEGER NOT NULL,
	VARIETY VARCHAR(20),
	QUANTITY INTEGER
);

INSERT INTO TOYS VALUES
	(1, 'Chew toy', 20),
	(2, 'Balls', 50),
	(3, 'Bowls', 30),
	(4, 'Fodable bed', 40);

ALTER TABLE TOYS
ALTER COLUMN VARIETY TYPE VARCHAR(30);

SELECT * FROM TOYS;

TRUNCATE TABLE TOYS;

DROP TABLE TOYS;