SELECT * FROM PETRESCUE;

SELECT AVG(COST/QUANTITY) FROM PETRESCUE WHERE ANIMAL='Dog';

SELECT DISTINCT UPPER(ANIMAL) FROM PETRESCUE;

SELECT * FROM PETRESCUE WHERE ANIMAL= 'cat';

SELECT * FROM PETRESCUE WHERE ANIMAL= 'Cat';

SELECT * FROM PETRESCUE WHERE LOWER(ANIMAL)= 'cat';

SELECT SUM(QUANTITY) FROM PETRESCUE WHERE EXTRACT(MONTH FROM RESCUEDATE)=05;

SELECT ID, RESCUEDATE, RESCUEDATE + INTERVAL '1 year' AS NEW_DATE
FROM PETRESCUE;
