SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;

SELECT * FROM EMPLOYEES WHERE JOB_ID IN (SELECT JOB_IDENT FROM JOBS WHERE 
	JOB_TITLE= 'Jr. Designer');

SELECT * FROM EMPLOYEES E, JOBS J WHERE E.JOB_ID = J.JOB_IDENT AND J.JOB_TITLE= 'Jr. Designer';
